version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ENTRY: 'service'
        ENVIRONMENT: '${ENVIRONMENT}'
    ports:
      - '3001:3001'
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
